import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import AuthProvider from './context/AuthProvider'
import { options } from "./api/auth/[...nextauth]/options"
import { getServerSession } from "next-auth/next"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TrocaPlantão App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, }: { children: React.ReactNode }) {
  const session = await getServerSession(options);
  console.log("sessao_layout:", session);

  return (
    <html lang="en">
      <body className={inter.className}>
          <AuthProvider>
            {session && (
              <Navbar />
            )}
            <div className='flex justify-center min-h-screen mt-5'>
              {children}
            </div>
          </AuthProvider>
      </body>
    </html>
  )
}
